#if !canImport(ObjectiveC)
import XCTest

extension FutureMapTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FutureMapTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FutureMapTests.__allTests__FutureMapTests),
    ]
}
#endif
